// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://deszonodkvxnqjwnvjmw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlc3pvbm9ka3Z4bnFqd252am13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0ODAyNzAsImV4cCI6MjA2OTA1NjI3MH0.OA9VhDyAJVxM1BkFGL5uN54sOyswCAJVO3FVPlsS9rw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});